##########################################################################
## - Some useful default values to modify the install
## - None of these are required to be changed as part of this guideß
## - For a full list of all attributes go to
##   https://github.com/concourse/concourse-chart/blob/master/values.yaml
##########################################################################
concourse:
  web:
    clusterName: concourse-test   ## a name for your cluster. can be anything
    bindIp: 0.0.0.0               ## bindport for the web service. currently expecting to be exposed to localhost
    runtime: containerd
    bindPort: 8080                ## once exposed, the service will be available outside the cluster at localhost:8080 
    localAuth:
      teams:
        - main                    ## team names. experiment with teams and RBAC
    auth:
      mainTeam:
        localUser: "test"         ## adds user "test" to the "main" team
  worker:
    runtime: containerd
    http_proxy: contractorproxywest.northgrum.com:80
    https_proxy: contractorproxywest.northgrum.com:80
    no_proxy:
      - localhost
      - 127.0.0.1
      - 10.96.0.0/12
      - 192.168.59.0/24
      - 192.168.49.0/24
      - 192.168.39.0/24
secrets:  
  localUsers: "test:test"         ## comma separated list of username:password for local auth users
